const fs = require('fs');
const p = 'd:/Project/DatabaseProject/airline-frontend/src/views/AdminView.vue';
let c = fs.readFileSync(p, 'utf8');

const modals = `\r\n\r\n    <!-- 城市编辑弹窗 -->\r\n    <div v-if=\\"cityModalVisible\\" class=\\"el-dialog__wrapper\\">\r\n      <div class=\\"el-dialog\\">\r\n        <div class=\\"el-dialog__header\\">\r\n          <span class=\\"el-dialog__title\\">{{ cityEditMode ? '编辑' : '新增' }}城市</span>\r\n          <button class=\\"el-dialog__headerbtn\\" @click=\\"cityModalVisible = false\\"><i class=\\"fas fa-times\\"></i></button>\r\n        </div>\r\n        <div class=\\"el-dialog__body\\">\r\n          <form class=\\"el-form\\">\r\n            <div class=\\"el-form-item\\"><label>城市代码</label><input v-model=\\"cityForm.area_code\\" class=\\"el-input__inner\\" placeholder=\\"如: SHA, PEK\\" :disabled=\\"cityEditMode\\"></div>\r\n            <div class=\\"el-form-item\\"><label>城市名称</label><input v-model=\\"cityForm.city_name\\" class=\\"el-input__inner\\" placeholder=\\"如: 上海\\"></div>\r\n            <div class=\\"el-form-item\\"><label>所属省份</label><input v-model=\\"cityForm.province\\" class=\\"el-input__inner\\" placeholder=\\"如: 上海市\\"></div>\r\n          </form>\r\n        </div>\r\n        <div class=\\"el-dialog__footer\\">\r\n          <button class=\\"el-button default\\" @click=\\"cityModalVisible = false\\">取消</button>\r\n          <button class=\\"el-button primary\\" @click=\\"handleCitySubmit\\">保存</button>\r\n        </div>\r\n      </div>\r\n    </div>\r\n\r\n    <!-- 机场编辑弹窗 -->\r\n    <div v-if=\\"airportModalVisible\\" class=\\"el-dialog__wrapper\\">\r\n      <div class=\\"el-dialog\\">\r\n        <div class=\\"el-dialog__header\\">\r\n          <span class=\\"el-dialog__title\\">{{ airportEditMode ? '编辑' : '新增' }}机场</span>\r\n          <button class=\\"el-dialog__headerbtn\\" @click=\\"airportModalVisible = false\\"><i class=\\"fas fa-times\\"></i></button>\r\n        </div>\r\n        <div class=\\"el-dialog__body\\">\r\n          <form class=\\"el-form\\">\r\n            <div class=\\"el-form-item\\"><label>机场代码</label><input v-model=\\"airportForm.airport_code\\" class=\\"el-input__inner\\" placeholder=\\"如: SHA, PVG\\" :disabled=\\"airportEditMode\\"></div>\r\n            <div class=\\"el-form-item\\"><label>机场名称</label><input v-model=\\"airportForm.airport_name\\" class=\\"el-input__inner\\" placeholder=\\"如: 上海虹桥国际机场\\"></div>\r\n            <div class=\\"el-form-item\\"><label>所属城市代码</label><input v-model=\\"airportForm.area_code\\" class=\\"el-input__inner\\" placeholder=\\"如: SHA\\"></div>\r\n          </form>\r\n        </div>\r\n        <div class=\\"el-dialog__footer\\">\r\n          <button class=\\"el-button default\\" @click=\\"airportModalVisible = false\\">取消</button>\r\n          <button class=\\"el-button primary\\" @click=\\"handleAirportSubmit\\">保存</button>\r\n        </div>\r\n      </div>\r\n    </div>`;

c = c.replace('      </main>\r\n    </div>', '      </main>' + modals + '\r\n    </div>');
fs.writeFileSync(p, c, 'utf8');
console.log('Phase 3c: modals done');
