const fs = require('fs');
const p = 'd:/Project/DatabaseProject/airline-frontend/src/views/AdminView.vue';
let c = fs.readFileSync(p, 'utf8');

const oldS = `// 保存逻辑\r\nconst saveEdit = () => {\r\n  if (!validateForm()) return\r\n\r\n  if (isAddMode.value) {\r\n    if(currentEditType.value === 'news') systemNews.value.unshift(editForm.value)\r\n    if(currentEditType.value === 'user') users.value.unshift(editForm.value)\r\n    if(currentEditType.value === 'flight') flights.value.unshift(editForm.value)\r\n    if(currentEditType.value === 'route') routes.value.unshift(editForm.value)\r\n    triggerToast('添加成功')\r\n  } else {\r\n    const updateTarget = (list) => {\r\n      const idx = list.findIndex(i => (i.id || i.flightNo) === (editForm.value.id || editForm.value.flightNo))\r\n      if(idx > -1) list[idx] = editForm.value\r\n    }\r\n    if(currentEditType.value === 'news') updateTarget(systemNews.value)\r\n    else if(currentEditType.value === 'user') updateTarget(users.value)\r\n    else if(currentEditType.value === 'flight') updateTarget(flights.value)\r\n    else if(currentEditType.value === 'route') updateTarget(routes.value)\r\n    else if(currentEditType.value === 'order') updateTarget(orders.value)\r\n    triggerToast('修改保存成功')\r\n  }\r\n  showEditModal.value = false\r\n}`;

const newS = `// 保存逻辑（重构：直连后端 API）\r\nconst saveEdit = async () => {\r\n  if (!validateForm()) return\r\n\r\n  // === 后端：航班新增 / 实例更新 ===\r\n  if (currentEditType.value === 'flight') {\r\n    try {\r\n      if (isAddMode.value) {\r\n        const res = await axios.post(API_BASE + '/admin/flight/add', {\r\n          flight_no: editForm.value.flightNo,\r\n          plane_model: editForm.value.aircraft,\r\n          first_class_num: editForm.value.fSeats,\r\n          economy_num: editForm.value.eSeats,\r\n          fly_duration: editForm.value.flyDuration || '120'\r\n        })\r\n        if (res.data.code === 200) {\r\n          triggerToast('航班 ' + editForm.value.flightNo + ' 创建成功（默认每周全周飞行）', 'success')\r\n          showEditModal.value = false\r\n        } else triggerToast(res.data.msg || '航班创建失败', 'error')\r\n      } else {\r\n        const res = await axios.post(API_BASE + '/admin/flight_instance/update', {\r\n          flight_no: editForm.value.flightNo,\r\n          fly_date: editForm.value.date || new Date().toISOString().slice(0,10),\r\n          flight_status: editForm.value.status || 'Scheduled',\r\n          first_remain: editForm.value.fSeats,\r\n          economy_remain: editForm.value.eSeats\r\n        })\r\n        if (res.data.code === 200) {\r\n          const idx = flights.value.findIndex(f => f.flightNo === editForm.value.flightNo)\r\n          if(idx > -1) flights.value[idx] = editForm.value\r\n          triggerToast('航班实例更新成功', 'success'); showEditModal.value = false\r\n        } else triggerToast(res.data.msg || '更新失败', 'error')\r\n      }\r\n      return\r\n    } catch (e) { triggerToast('请求失败: ' + (e.response?.data?.msg || e.message), 'error'); return }\r\n  }\r\n\r\n  // === 纯前端模拟 ===\r\n  const updateList = (list) => {\r\n    const idx = list.findIndex(i => (i.id || i.flightNo) === (editForm.value.id || editForm.value.flightNo))\r\n    if(idx > -1) list[idx] = editForm.value\r\n  }\r\n  if (isAddMode.value) {\r\n    if(currentEditType.value === 'news') systemNews.value.unshift(editForm.value)\r\n    if(currentEditType.value === 'user') users.value.unshift(editForm.value)\r\n    if(currentEditType.value === 'route') routes.value.unshift(editForm.value)\r\n    triggerToast('添加成功')\r\n  } else {\r\n    if(currentEditType.value === 'news') updateList(systemNews.value)\r\n    else if(currentEditType.value === 'user') updateList(users.value)\r\n    else if(currentEditType.value === 'route') updateList(routes.value)\r\n    else if(currentEditType.value === 'order') updateList(orders.value)\r\n    triggerToast('修改保存成功')\r\n  }\r\n  showEditModal.value = false\r\n}`;

c = c.replace(oldS, newS);
fs.writeFileSync(p, c, 'utf8');
console.log('saveEdit refactored');
